"""The toolbox presets must describe outcomes the runtime actually produces."""

from __future__ import annotations

import json
from typing import Any

import pytest

from scripts.build_toolbox_presets import (
    BASE_SCENARIO,
    PRESETS,
    PresetGenerationError,
    build,
    outcome_class,
    render,
    scenario_for,
)


@pytest.fixture(scope="module")
def payload() -> dict[str, Any]:
    """Building runs 260 paired rollouts; do it once for the whole module."""

    return build()


def test_declared_mix_matches_the_published_contract(payload: dict[str, Any]) -> None:
    assert payload["summary"] == {
        "total": 10,
        "ppoSolved": 8,
        "heuristicSolved": 3,
        "neitherSolved": 2,
    }
    assert len(payload["presets"]) == 10
    assert len({preset["id"] for preset in payload["presets"]}) == 10


def test_every_preset_records_the_verdicts_the_engine_returned(payload: dict[str, Any]) -> None:
    for preset in payload["presets"]:
        observed = preset["observed"]
        assert (
            outcome_class(observed["candidateSolved"], observed["baselineSolved"])
            == preset["outcome"]
        )


def test_no_preset_is_solved_by_the_heuristic_alone(payload: dict[str, Any]) -> None:
    assert not [
        preset
        for preset in payload["presets"]
        if preset["observed"]["baselineSolved"]
        and not preset["observed"]["candidateSolved"]
    ]


def test_each_preset_class_is_typical_of_its_configuration(payload: dict[str, Any]) -> None:
    # A class reached on one lucky seed would misrepresent the named scenario.
    for preset in payload["presets"]:
        assert preset["classShareFirst25Seeds"] >= 9


def test_rendering_is_stable_for_one_payload(payload: dict[str, Any]) -> None:
    # Build-to-build determinism is covered by the CI `--check` byte compare.
    assert render(payload) == render(payload)


def test_declared_class_is_enforced_rather_than_recorded(monkeypatch: Any) -> None:
    """A preset whose label stops matching the runtime must fail the build."""

    mislabelled = list(PRESETS)
    identifier, label, note, _declared, overrides = mislabelled[0]
    mislabelled[0] = (identifier, label, note, "neither", overrides)
    monkeypatch.setattr(
        "scripts.build_toolbox_presets.PRESETS", tuple(mislabelled)
    )

    with pytest.raises(PresetGenerationError) as excinfo:
        build()

    assert identifier in str(excinfo.value)


def test_scenarios_stay_on_the_canonical_protocol() -> None:
    for identifier, label, _note, _declared, overrides in PRESETS:
        scenario = scenario_for(label, overrides)
        assert scenario["name"] == label, identifier
        assert scenario["horizon_days"] == BASE_SCENARIO["horizon_days"]
        assert scenario["assessment_tail_days"] == BASE_SCENARIO["assessment_tail_days"]
        assert scenario["severity_min"] <= scenario["severity_max"]
        assert scenario["forced_shock"] is None
        assert scenario["forced_shocks"] == []


def test_rendered_module_is_valid_generated_typescript(payload: dict[str, Any]) -> None:
    rendered = render(payload)

    assert rendered.startswith("/* This file is generated by")
    assert "Do not hand-edit it" in rendered
    assert rendered.rstrip().endswith("as const")
    body = rendered[rendered.index("= {") + 2 : rendered.rindex("} as const") + 1]
    assert json.loads(body)["summary"]["total"] == 10
