"""Compatibility facade for historical versioned scenario imports."""

from backend.app.city.scenarios import (
    DEVELOPMENT_FAMILIES,
    DEVELOPMENT_SEEDS,
    FINAL_FAMILIES,
    FINAL_SEEDS,
    TRAINING_FAMILIES,
    TRAINING_SEEDS,
    ScenarioFamily,
)

ScenarioFamilyV3 = ScenarioFamily
TRAINING_FAMILIES_V3 = TRAINING_FAMILIES
DEVELOPMENT_FAMILIES_V3 = DEVELOPMENT_FAMILIES
FINAL_FAMILIES_V3 = FINAL_FAMILIES
TRAINING_SEEDS_V3 = TRAINING_SEEDS
DEVELOPMENT_SEEDS_V3 = DEVELOPMENT_SEEDS
FINAL_SEEDS_V3 = FINAL_SEEDS

__all__ = (
    "DEVELOPMENT_FAMILIES_V3",
    "DEVELOPMENT_SEEDS_V3",
    "FINAL_FAMILIES_V3",
    "FINAL_SEEDS_V3",
    "ScenarioFamilyV3",
    "TRAINING_FAMILIES_V3",
    "TRAINING_SEEDS_V3",
)
